import { Key } from '@nut-tree-fork/nut-js';

export const KEY_MAP: Record<string, Key> = {
    'backspace': Key.Backspace,
    'enter': Key.Enter,
    'return': Key.Enter,
    'tab': Key.Tab,
    'escape': Key.Escape,
    'esc': Key.Escape,
    'delete': Key.Delete,
    'del': Key.Delete,
    'home': Key.Home,
    'end': Key.End,
    'pageup': Key.PageUp,
    'pgup': Key.PageUp,
    'pagedown': Key.PageDown,
    'pgdn': Key.PageDown,
    'arrowup': Key.Up,
    'arrowdown': Key.Down,
    'arrowleft': Key.Left,
    'arrowright': Key.Right,
    'shift': Key.LeftShift,
    'control': Key.LeftControl,
    'ctrl': Key.LeftControl,
    'alt': Key.LeftAlt,
    'meta': Key.LeftSuper,
    'super': Key.LeftSuper,
    'space': Key.Space,
};
